# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/messages_*.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated_plugin_registrant.dart
    - ios/**
linter:
  rules:
    # VS Codeでfreezedの警告が消えない問題があるため妥協
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
